{
  "world": {
    "package": "tau2",
    "version": "1.0.1",
    "revision": "2174a603f6d014ef94473ffa95957f6ce27100db",
    "split": "retail/base"
  },
  "tasks": [
    "tau2.retail.33.json",
    "tau2.retail.34.json"
  ],
  "exclusions": []
}
